#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/luoda/luoda /usr/bin/luoda

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/luoda.service ]; then
			rm /etc/systemd/system/luoda.service /usr/lib/systemd/system/luoda.service /usr/lib/systemd/user/luoda.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/luoda/files/systemd/luoda.service /usr/lib/systemd/system/luoda.service
		# try fix error in Ubuntu 18.04
		# Failed to reload luoda.service: Unit luoda.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/luoda.service:10: Executable path is not absolute: pkill -f "luoda --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/luoda.service
		fi
		systemctl daemon-reload
		systemctl enable luoda
		systemctl start luoda
	fi
fi
